#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Frank Müller, fm@sysinit.de

# Work in progess!


hp_msa_status_map = { 0: "unkown" , 1: "unknown", 2: "unkown", 3: "ok", 4: "warning", 5: "critical" }
hp_msa_status2nagios_map = { 'ok': 0, 'disabled' : 1, 'degraded': 2, 'failed': 2, 'unkown' : 3 }

def inventory_hp_msa(checkname, info):
	if len(info) > 0:
		return [ ( line[0], None ) for line in info ]
	else:
		return []

def check_hp_msa(item, params, info):
	for line in info:
		if line[0] == item:
			index, name, status = line
			snmp_status = hp_msa_status_map[int(status)]
			status	    = hp_msa_status2nagios_map[snmp_status]
			return (status, '%s' % (snmp_status)) 
	return (3, "UNKNOWN - item not found in snmp data")

check_info['hp_msa'] = (check_hp_msa, "MSA Overall Status %s", 0, inventory_hp_msa)

snmp_info["hp_msa"] = ( ".1.3.6.1.3.94.1.8.1", [
					"2.32.128.0.192.255.218.147.4.0.0.0.0.0.0.0.0.23", # Index 
					"3.32.128.0.192.255.218.147.4.0.0.0.0.0.0.0.0.23", # Name
					"4.32.128.0.192.255.218.147.4.0.0.0.0.0.0.0.0.23",  # Status, INT
#					"6.1.8.32.128.0.192.255.218.147.4.0.0.0.0.0.0.0.0", # Serial
#					"7.1.3.32.128.0.192.255.218.147.4.0.0.0.0.0.0.0.0.1", # Ctrl A FW
#					"7.1.3.32.128.0.192.255.218.147.4.0.0.0.0.0.0.0.0.2", # Ctrl B FR
			 ] )
